// Generated by Codex audit — review before merging
import { describe, it } from "vitest";

describe("Seller Images API", () => {
  // Suggested helpers:
  // - signUpTestUser / grantSellerRole
  // - createTestInventoryItem
  // - authedRequest
  // - r2 mocks in seller-profile.test.ts

  it.todo("POST /api/v1/seller/inventory/:id/images/upload-url happy path");
  it.todo("POST /api/v1/seller/inventory/:id/images/upload-url auth rejection");
  it.todo("POST /api/v1/seller/inventory/:id/images/upload-url invalid input");
  it.todo("POST /api/v1/seller/inventory/:id/images/upload-url domain edge case: archived item or image limit");

  it.todo("POST /api/v1/seller/inventory/:id/images/:imageId/confirm happy path");
  it.todo("POST /api/v1/seller/inventory/:id/images/:imageId/confirm auth rejection");
  it.todo("POST /api/v1/seller/inventory/:id/images/:imageId/confirm invalid input");
  it.todo("POST /api/v1/seller/inventory/:id/images/:imageId/confirm domain edge case: missing storage object marks upload failed");

  it.todo("PATCH /api/v1/seller/inventory/:id/images/order happy path");
  it.todo("PATCH /api/v1/seller/inventory/:id/images/order auth rejection");
  it.todo("PATCH /api/v1/seller/inventory/:id/images/order invalid input");
  it.todo("PATCH /api/v1/seller/inventory/:id/images/order domain edge case: multiple primaries rejected");

  it.todo("DELETE /api/v1/seller/inventory/:id/images/:imageId happy path");
  it.todo("DELETE /api/v1/seller/inventory/:id/images/:imageId auth rejection");
  it.todo("DELETE /api/v1/seller/inventory/:id/images/:imageId invalid input");
  it.todo("DELETE /api/v1/seller/inventory/:id/images/:imageId domain edge case: deleting final ready image pauses active listings");
});
