// Generated by Codex audit — review before merging
import { describe, it } from "vitest";

describe("Shared contract: auth.ts", () => {
  it.skip("maps signupRequestSchema to a response contract", () => {
    // Better Auth owns the request/response format for /api/auth/*.
    // Current shared auth schemas need an explicit compatibility decision first.
  });

  it.skip("maps signinRequestSchema to a response contract", () => {
    // Better Auth owns the request/response format for /api/auth/*.
    // Current shared auth schemas need an explicit compatibility decision first.
  });

  it.skip("maps authResponseSchema to a Better Auth endpoint", () => {
    // The live Better Auth response shape does not currently have a vetted
    // one-to-one mapping to packages/types/src/auth.ts.
  });
});
