// Generated by Codex audit — review before merging
import { describe, it, expect } from "vitest";
import { channelResponseSchema } from "@bushpop/types/channel";
import { publicRequest } from "../../helpers/http.js";

describe("Shared contract: channel.ts", () => {
  it("GET /api/v1/store/channels/current matches channelResponseSchema", async () => {
    const res = await publicRequest("GET", "/api/v1/store/channels/current");

    expect(res.statusCode).toBe(200);

    const parsed = channelResponseSchema.safeParse(res.json());
    expect(parsed.success).toBe(true);
  });
});
