// Generated by Codex audit — review before merging
import { describe, it, expect, beforeEach, vi } from "vitest";
import { CartSchema, CheckoutSessionSchema } from "@bushpop/types";
import { signUpTestUser, grantSellerRole } from "../../helpers/auth.js";
import { createActiveTestListing } from "../../helpers/create-listing.js";
import { authedRequest } from "../../helpers/http.js";
import { createStripeReadySeller } from "../../helpers/stripe-mock.js";

vi.mock("../../../lib/stripe.js", () => {
  const mockPaymentIntent = {
    id: "pi_contract_mock",
    client_secret: "pi_contract_mock_secret",
    status: "requires_payment_method",
    amount: 0,
    currency: "aud",
    transfer_group: null,
    metadata: {},
  };

  return {
    getStripe: vi.fn(() => ({
      paymentIntents: {
        create: vi.fn().mockResolvedValue(mockPaymentIntent),
        cancel: vi.fn().mockResolvedValue({ ...mockPaymentIntent, status: "canceled" }),
      },
      refunds: {
        create: vi.fn().mockResolvedValue({ id: "re_contract_mock", amount: 0 }),
      },
      transfers: {
        create: vi.fn().mockResolvedValue({ id: "tr_contract_mock", amount: 0, currency: "aud" }),
      },
      webhooks: {
        constructEvent: vi.fn(),
      },
    })),
    _resetStripe: vi.fn(),
  };
});

vi.mock("../../../workers/checkout-expiry.js", () => ({
  scheduleCheckoutExpiry: vi.fn().mockResolvedValue(undefined),
  startCheckoutExpiryWorker: vi.fn(),
  CHECKOUT_EXPIRY_QUEUE: "checkout-expiry",
}));

vi.mock("../../../workers/email.js", () => ({
  enqueueEmail: vi.fn().mockResolvedValue(undefined),
  startEmailWorker: vi.fn(),
  EMAIL_QUEUE: "email",
}));

vi.mock("../../../workers/shipping-label.js", () => ({
  enqueueShippingLabel: vi.fn().mockResolvedValue(undefined),
  startShippingLabelWorker: vi.fn(),
  SHIPPING_LABEL_QUEUE: "shipping-label",
}));

function normalizeCart(body: {
  createdAt: string;
  updatedAt: string;
  items: Array<{ createdAt: string }>;
}) {
  return {
    ...body,
    createdAt: new Date(body.createdAt),
    updatedAt: new Date(body.updatedAt),
    items: body.items.map((item) => ({
      ...item,
      createdAt: new Date(item.createdAt),
    })),
  };
}

function normalizeCheckoutSession(body: {
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string;
}) {
  return {
    ...body,
    expiresAt: body.expiresAt ? new Date(body.expiresAt) : null,
    createdAt: new Date(body.createdAt),
    updatedAt: new Date(body.updatedAt),
  };
}

const TEST_ADDRESS = {
  line1: "123 George Street",
  suburb: "Sydney",
  state: "NSW",
  postcode: "2000",
  country: "AU",
};

describe("Shared contract: commerce.ts", () => {
  let buyerToken: string;
  let sellerId: string;

  beforeEach(async () => {
    vi.clearAllMocks();

    const buyer = await signUpTestUser();
    buyerToken = buyer.sessionToken;

    const seller = await signUpTestUser();
    sellerId = seller.user.id;

    await grantSellerRole(sellerId, { withDefaultAddress: true });
    await createStripeReadySeller(sellerId);
  });

  it("GET /api/v1/store/cart matches CartSchema after JSON date revival", async () => {
    const listing = await createActiveTestListing(sellerId, { priceCents: 5000 });

    const addRes = await authedRequest(buyerToken, "POST", "/api/v1/store/cart/items", {
      listingId: listing.id,
    });
    expect(addRes.statusCode).toBe(200);

    const cartRes = await authedRequest(buyerToken, "GET", "/api/v1/store/cart");
    expect(cartRes.statusCode).toBe(200);

    const parsed = CartSchema.safeParse(normalizeCart(cartRes.json()));
    expect(parsed.success).toBe(true);
  });

  it("GET /api/v1/store/checkout/:id matches CheckoutSessionSchema after JSON date revival", async () => {
    const listing = await createActiveTestListing(sellerId, { priceCents: 5000 });

    const addRes = await authedRequest(buyerToken, "POST", "/api/v1/store/cart/items", {
      listingId: listing.id,
    });
    expect(addRes.statusCode).toBe(200);

    const addressRes = await authedRequest(buyerToken, "POST", "/api/v1/addresses", TEST_ADDRESS);
    expect(addressRes.statusCode).toBe(201);

    const checkoutRes = await authedRequest(buyerToken, "POST", "/api/v1/store/checkout", {
      shippingAddressId: addressRes.json().id,
    });
    expect(checkoutRes.statusCode).toBe(200);

    const sessionId = checkoutRes.json().sessionId as string;
    const sessionRes = await authedRequest(buyerToken, "GET", `/api/v1/store/checkout/${sessionId}`);
    expect(sessionRes.statusCode).toBe(200);

    const parsed = CheckoutSessionSchema.safeParse(normalizeCheckoutSession(sessionRes.json()));
    expect(parsed.success).toBe(true);
  });

  it.skip("GET /api/v1/store/orders/:id matches OrderSchema (and nested AddressSnapshotSchema / OrderItemSchema / OrderStatusSchema)", () => {
    // packages/types/src/commerce.ts is already Phase 2B-aware, but the live
    // store-order HTTP schema in packages/api/src/routes/v1/store/orders/schemas.ts
    // still exposes the older Phase 2A response shape.
  });

  it.skip("maps MoneySchema and MoneySnapshotSchema to a dedicated HTTP response", () => {
    // Current endpoints expose money fields inline rather than as a shared money object.
  });

  it.skip("maps AddToCartInputSchema and InitiateCheckoutInputSchema as raw response contracts", () => {
    // Request-only schemas.
  });

  it.skip("maps PayoutHoldSchema and PayoutHoldStatusSchema to a public endpoint", () => {
    // No current buyer/seller-facing payout-hold endpoint exists.
  });

  it.skip("maps RefundSchema and RefundStatusSchema to a public endpoint", () => {
    // Refund API surface is not implemented in the current repo reality.
  });

  it.skip("maps PaymentOperationSchema / PaymentOperationTypeSchema / PaymentOperationStatusSchema to a public endpoint", () => {
    // Payment-operation API surface is not implemented in the current repo reality.
  });

  it.skip("maps BuyerDisplayStatusSchema to a public endpoint", () => {
    // Buyer display status exists in shared types but is not yet emitted by the live API.
  });
});
