// Generated by Codex audit — review before merging
import { describe, it, expect } from "vitest";
import { roleSchema } from "@bushpop/types/roles";
import { signUpTestUser, grantSellerRole } from "../../helpers/auth.js";
import { authedRequest } from "../../helpers/http.js";

describe("Shared contract: roles.ts", () => {
  it("GET /api/v1/customer/me exposes roles that match roleSchema", async () => {
    const { user, sessionToken } = await signUpTestUser();
    await grantSellerRole(user.id);

    const res = await authedRequest(sessionToken, "GET", "/api/v1/customer/me");

    expect(res.statusCode).toBe(200);

    const body = res.json() as { roles: string[] };
    for (const role of body.roles) {
      expect(roleSchema.parse(role)).toBe(role);
    }
  });
});
