// Generated by Codex audit — review before merging
import { describe, it, expect } from "vitest";
import { userResponseSchema } from "@bushpop/types/user";
import { signUpTestUser } from "../../helpers/auth.js";
import { authedRequest } from "../../helpers/http.js";

describe("Shared contract: user.ts", () => {
  it("GET /api/v1/customer/me user matches userResponseSchema", async () => {
    const { sessionToken } = await signUpTestUser();

    const res = await authedRequest(sessionToken, "GET", "/api/v1/customer/me");

    expect(res.statusCode).toBe(200);

    const body = res.json() as { user: unknown };
    const parsed = userResponseSchema.safeParse(body.user);
    expect(parsed.success).toBe(true);
  });

  it.skip("maps a public endpoint to userSchema", () => {
    // Current public responses omit createdAt/updatedAt, so there is no direct
    // raw HTTP contract for the full userSchema yet.
  });
});
